version: '3.3'

services:

  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=inno_wise
      - POSTGRES_PASSWORD=innowise
      - POSTGRES_DB=inno_wise
  django:
    container_name: inno_wise
    build:
      context: ./
      dockerfile: Dockerfile
    command: ./run-server.sh
    volumes:
      - .:/usr/src/inno_test
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      
       
volumes:
  pg_data: